# frozen_string_literal: true
ruby "2.6.3"

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "faraday"
gem "faraday_middleware"
gem "nokogiri"
gem "nokogumbo"
